<?php
/**
 * @package Magedelight_Customerprice for Magento 2
 * @author MageDelight Team
 * @copyright Copyright (c) MageDelight (https://www.magedelight.com) owned by Krish TechnoLabs. All Rights reserved.
 */
?>
<?php
use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$customHelper = $this->helper('Magedelight\Customerprice\Helper\Data');
$customerPriceIsEnabled = $customHelper->getConfig('customerprice/general/enable');
if ($block->getmoduleStatus()) {
    ?>
    <?php if ($_productCollection && count($_productCollection)): ?>
   
        <?= /* @noEscape */ $block->getToolbarHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
    
        $pos = $block->getPositioned();
        ?>


<div class="products wrapper <?= /* @noEscape */ $viewMode; ?> products-<?= /* @noEscape */ $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):
                //echo "<pre>"; print_r(get_class_methods($_product)); exit;
                ?>
                <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li>
                <li class="item product product-item">' ?>
                <div class="product-item-info" id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>"
                        class="product photo product-item-photo" tabindex="-1">
                        <?= /* @noEscape */ $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @noEscape */ $_product->getProductUrl() ?>">
                                <?= /* @noEscape */ $_helper->productAttribute(
                                    $_product,
                                    $_product->getName(),
                                    'name'
                                ); ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */ $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?= /* @noEscape */ $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?=
                            /* @noEscape */ strpos((string)$pos, $viewMode . '-actions') ?
                            $position : ''; ?>>
                                <div class="actions-primary"<?=
                                /* @noEscape */ strpos((string)$pos, $viewMode . '-primary') ?
                                    $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?=
                                        /* @noEscape */ $postParams['action']; ?>"
                                         method="post">
                                            <input type="hidden" name="product" value="<?=
                                            /* @noEscape */ $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?= /* @noEscape */
                                            Action::PARAM_NAME_URL_ENCODED; ?>"
                                            value="<?= /* @noEscape */ $postParams['data']
                                            [Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?= /* @noEscape */$block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span>
                                            <?= /* @noEscape */ __('In stock') ?></span>
                                            </div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span>
                                            <?= /* @noEscape */ __('Out of stock') ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"
                                    <?= /* @noEscape */ strpos((string)$pos, $viewMode . '-secondary') ? $position : ''; //@codingStandardsIgnoreStart ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?= /* @noEscape */ $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?= /* @noEscape */ $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?= /* @noEscape */ __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    //@codingStandardsIgnoreEnd
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?= /* @noEscape */ $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?= /* @noEscape */ $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?= /* @noEscape */  $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?= /* @noEscape */ __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>"
                                       title="<?= /* @noEscape */ $_product->getName() ?>"
                                       class="action more"><?= /* @noEscape */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= /* @noEscape */($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>

        <?php if ($block->getPagerHtml()): ?>
         <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
        <?php endif ?>
        <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
  
    <?php else: ?>
    <div class="message info empty"><span><?= /* @noEscape */ __('No products found.'); ?></span></div>
    <?php endif;
}
?>
<style>
    .md_customerprice-index-offers.page-layout-1column .sidebar.sidebar-additional {
        display: none;
    }
</style>

<script>
    require(['jquery',
        'jquery/ui',
        'mage/mage',
        'mage/translate'
    ], function ($) {
        if ($("body").hasClass("page-layout-1column") && $("body").hasClass("md_customerprice-index-offers")) {
            $(".sidebar.sidebar-main").prependTo(".column.main");
        }
    });
</script>