<?php
use Magento\Framework\App\Action\Action;
$helper = $this->helper('Magebees\Wholesaleconfigurable\Helper\Data');
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <?php foreach ($_attributes as $_attribute): ?>
        <div class="field configurable required" style="display:none;">
            <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
            </label>
            <div class="control">
                <select name="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-selector="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-validate="{required:true}"
                        id="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>"
                        class="super-attribute-select">
                    <option value=""><?= /* @escapeNotVerified */ __('Choose an Option...') ?></option>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "gallerySwitchStrategy": "<?php /* @escapeNotVerified */ echo $block->getVar('gallery_switch_strategy',
                        'Magento_ConfigurableProduct') ?: 'replace'; ?>"
                }
            }
        }
    </script>
<?php endif;?>

<form  id="saveForm"  method="post"> </form>
<?php
$wholesaleHelper = $this->helper('Magebees\Wholesaleconfigurable\Helper\Data');
$obj = $helper->getObjectManager();
$productId = $block->getProduct()->getId();
$product = $obj->create('Magento\Catalog\Model\ProductRepository')
               ->getById($productId);
$configurableProduct = $obj->get('Magento\ConfigurableProduct\Helper\Data');
$helper = $wholesaleHelper;
$groupAttribute = explode(",", $wholesaleHelper->getGroupAttribute());
$hidePrice = $wholesaleHelper->getHidePrice();
$eachRowAddtocart = $helper->eachRowAddtocart();
$expandno = $helper->getExpandNo();
if(!$expandno){
	$expandno = 3;
}else{
	$expandno = $expandno-1;
}
$cntprice = $obj->create('Magento\Catalog\Model\Product\Type\Price');

$productAttributes = $product->getTypeInstance(false)->getConfigurableAttributes($product);
$serlData = $wholesaleHelper->getChildrenInfo($product,$productAttributes);
$configurable_products = $helper->getserData(($serlData));
$itemsIds = array();
$cartIds = array();
$actionName = $helper->getActionName();
if($actionName == "checkout_cart_configure"){
	$currentProductId = $helper->getCurrentProductId();
	$cartProduct = $helper->getCartProduct($currentProductId);
	if($cartProduct) {
		$itemsIds =  $helper->getCartItems();
		$cartIds =  $helper->getCartId();
	}
}
$totalOption = count($configurable_products['products']);
$disabled = '';
?>
<?php if($totalOption > ($expandno+1)){ ?>
<div onclick="expandCollapse()" id="expand-collapse-top" class="expand-collapse-top" align="right"><?php echo __('Expand All Options'); ?></div>
<?php } ?>
<div id="wholesale-configurable" class="table-wrapper">
	<table class="configurable-product-table data-table cart-table data table">
			<thead>
				<tr class="first last">
					<input type="hidden" name="configurable_grid_table" value="Yes" />
					<input type="hidden" name="products" value="<?php echo $productId; ?>"/>
					<?php foreach($configurable_products['labels'] as $_label ) : ?>
						<th class="a-center attributes" data-th="Size"><?php echo $_label; ?></th>
					<?php endforeach ?>
					<?php if (in_array("availability", $groupAttribute)): ?>
						<th class="a-center avaibility" data-th="Availability"><?php echo __('Availability'); ?></th>
					<?php endif;?>
					<?php if($hidePrice): ?>
						<?php if (in_array("unitprice", $groupAttribute)): ?>
							<th class="a-center unit" data-th="Unit Price"><?php echo __('Unit Price'); ?></th>
						<?php endif;?>
					<?php endif;?>
					<?php
						$childProducts = $obj->create('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getUsedProducts($_product,null);

	                    foreach($childProducts as $child) {
							$childId = $child->getId();
							$childProduct = $obj->create('Magento\Catalog\Model\Product')->load($childId);
							break;
						}
					?>
					<?php $productInfoTh = 0; ?>

				<th class="a-center qty" data-th="Qty"><?php echo __('Qty'); ?></th>

				<?php if($hidePrice): ?>
					<?php if (in_array("subtotal", $groupAttribute)): ?>
						<th class="a-center price" data-th="Subtotal"><?php echo __('Subtotal'); ?></th>
					<?php endif;?>
				<?php endif;?>
				<?php if($eachRowAddtocart) { ?>
					<th class="a-center Action" data-th="Action"><?php echo __('Action'); ?></th>
				<?php } ?>
			</tr>
		</thead>
		<tbody>
			<?php $i = 0; ?>
			<?php foreach($configurable_products['products'] as $productVal) : ?>
				<?php
					$childrenId = $productVal['info']['prod_id'];
					$productInfo = $obj->create('Magento\Catalog\Model\Product')->load($childrenId);
					$childrenName = $productInfo->getName();
					$tier_price = $productVal['info']['tier_price'];
				?>
				<tr  <?php if($i > $expandno) { ?> class="cws-config-line toggle_container cws-<?php echo $i; ?>" style="display:none;" <?php }else{ ?> class="cws-config-line cws-<?php echo $i; ?>" <?php } ?>>

					<input type="hidden" value="<?php echo "cws-".$i; ?>" name="row_name[<?php echo $childrenId; ?>]">

					<?php
						$att_price = 0;
						foreach($productVal['attributes'] as $att) : ?>

							<?php $hidden_super_val = '<input type="hidden" name="super_attribute['.$childrenId.']['.$att['attribute_id'].']" class="cws-attribute-select"  value="'.$att['option_id'].'" data-label="'.$att['attribute_id'].'" data-childid ="'.$childrenId.'">';
					?>

					<td class="a-center attributes" data-th="Size">

					 <?php switch ($att['swatch_type']) {
                        case '3':
                            ?>
                            <div class="swatch-option cws <?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                 tabindex="-1"
                                 option-type="3"
								 data-label="<?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                 option-id="<?= /* @escapeNotVerified */ $att['option_id']; ?>"
                                 option-label="<?= /* @escapeNotVerified */ $att['value'] ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                                ></div>
                            <?php    break;
                        case '2':
                            ?>
                            <?php
								$swatchProduct = $obj->create('Magento\Swatches\Block\LayeredNavigation\RenderLayered');

								$swatchThumbPath = $swatchProduct->getSwatchPath('swatch_thumb',  $att['swatch_value']);
								$swatchImagePath = $swatchProduct->getSwatchPath('swatch_image',  $att['swatch_value']);
						     ?>
                            <div class="swatch-option cws image <?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                 tabindex="-1"
                                 option-type="2"
								 data-label="<?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                 option-id="<?= /* @escapeNotVerified */ $att['option_id']; ?>"
                                 option-label="<?= /* @escapeNotVerified */ $att['value'] ?>"
                                 option-tooltip-thumb="<?= /* @escapeNotVerified */ $swatchThumbPath ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?= /* @escapeNotVerified */ $swatchImagePath ?>) no-repeat center; background-size: initial;"></div>
                            <?php    break;
                        case '1':
                            ?>

							<div class="swatch-option cws color <?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
									 tabindex="-1"
								 	 data-label="<?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
									 option-type="1"
									 option-id="<?= /* @escapeNotVerified */ $att['option_id']; ?>"
									 option-label="<?= /* @escapeNotVerified */ $att['value'] ?>"
									 option-tooltip-thumb=""
									 option-tooltip-value="<?= /* @escapeNotVerified */ $att['swatch_value'] ?>"
									 style="background: <?= /* @escapeNotVerified */ $att['swatch_value'] ?> no-repeat center; background-size: initial;"></div>



                            <?php    break;
                        case '0':
                        default:
                            ?>
                                <div class="swatch-option cws text <?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                     tabindex="-1"
									 data-label="<?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                     option-type="0"
                                     option-id="<?= /* @escapeNotVerified */ $att['option_id']; ?>"
                                 	 option-label="<?= /* @escapeNotVerified */ $att['value'] ?>"
                                     option-tooltip-thumb=""
                                     option-tooltip-value=""
                                    ><?= /* @escapeNotVerified */ $att['swatch_value'] ?></div>
                            <?php    break;
		 					 case '5':
                            ?>
                            <div class="select-option cws <?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                 tabindex="-1"
								 data-label="<?= /* @escapeNotVerified */ $att['attribute_id']; ?>"
                                 option-id="<?= /* @escapeNotVerified */ $att['option_id']; ?>"
                                 option-label="<?= /* @escapeNotVerified */ $att['value'] ?>"
                                 option-tooltip-value="<?= /* @escapeNotVerified */ $att['value'] ?>"
                                ><?= /* @escapeNotVerified */ $att['value'] ?></div>
                            <?php    break;
                    } ?>


						<?php echo $hidden_super_val;?>
					</td>
			<?php endforeach ?>

			<?php if (in_array("availability", $groupAttribute)): ?>
				<?php
					$qty_label = '';

					if(($productVal['info']['qty'] >= 1 && $productVal['info']['status_stock'] == 1)){
						$qty_label =  $productVal['info']['qty'];
						$disabled = '';
					}elseif($productVal['info']['status_stock'] == 0){
						$qty_label = __('Out of stock');
						$disabled = 'readonly';
					}else{
						 $qty_label = __('Unlimited');
						 $disabled = '';
					}
				?>
				<td class="a-center avaibility" data-th="Avaibility">
					<?php echo $qty_label; 	?>
				</td>
			<?php endif; ?>
			<!-- Start Add Unit Price -->

			<?php
				$att_price = 0;
				$priceHelper = $obj->create('Magento\Framework\Pricing\Helper\Data');
				$cartqty = '0';
				$cartId = '';
				if (array_key_exists($childrenId, $itemsIds)) {
					$cartqty = $itemsIds[$childrenId];
					$cartId = $cartIds[$childrenId];
				}
				if($cartqty) {
					$subtotal = $helper->getSubTotal($cartqty,$productInfo->getId());
				}else{
					$subtotal = "0.00";
				}
				$cwsfinalprice = $priceHelper->currency($subtotal, true, false);
				$subtotal =  $subtotal * $cartqty;
				$finalsubtotal =  $priceHelper->currency($subtotal, true, false);
				?>
			<?php if($hidePrice): ?>
				<?php if (in_array("unitprice", $groupAttribute)): ?>
					<td class="a-center unit" data-th="Unit Price">
						<?php echo $tier_price; ?>
						<?php if($productInfo->getSpecialPrice()):?>
							<p class="special-price">
								<span class="price finalcwsprice">
									<?php $prdPrice = number_format($helper->getHasSpecialPrice($productInfo) + $att_price,2); ?>
									<?php echo $priceHelper->currency($prdPrice, true, false); ?>
								</span>
							</p>
							<p class="old-price">
								<span class="price">
									<?php $prdPrices = number_format($productInfo->getPrice()+ $att_price,2); ?>
									<?php echo $priceHelper->currency($prdPrices, true, false); ?>
								</span>
							</p>
						<?php else:?>
							<span class="regular-price">
								<span class="price finalcwsprice">
								<?php if($cartqty) { ?>
									<?php echo $cwsfinalprice; ?>
								<?php }else{ ?>
									<?php $prdFinalPrice = number_format($productInfo->getFinalPrice() + $att_price,2); ?>
									<?php echo $priceHelper->currency($prdFinalPrice, true, false); ?>
								<?php } ?>

								</span>
							</span>
						<?php endif;?>
					</td>
				<?php endif; ?>
			<?php endif; ?>


			<!-- End Add Unit Price -->


			<td class="a-center qty" data-th="Qty">
			<?php if ($qty_label != 'Out of stock'){ ?>
				<div class="qty-box">
				<?php
					$arr = array();
					foreach ($productVal['attributes'] as $productAttr) {
						$arr[$productAttr['attribute_id']] = $productAttr['option_id'];
					}

				?>
				<?php if($cartId) { ?>
					<input type="hidden" value="<?php echo $cartId; ?>" name="cartid[<?php echo $childrenId; ?>]">
				<?php }else{ ?>
					<input type="hidden" value="add" name="cartid[<?php echo $childrenId; ?>]">
				<?php } ?>
					<input id="down" class="config-down-qty-button" value="-"  type="button">
					<input type="text" min="0" data-id="<?php echo $childrenId.'_'.$_product->getId();?>" name="config_table_qty[<?php echo $childrenId; ?>]" value="<?php echo $cartqty; ?>" <?php echo $disabled; ?> id="super_group_qty_<?php echo $childrenId;?>" class="input-text qty config_qty" data-label="<?php echo $childrenId; ?>" onkeypress="javascript:return isNumber(event)">
				<input id="up" class="config-up-qty-button" value="+"  type="button">
				<input type="hidden" class="price_<?php echo $childrenId.'_'.$_product->getId();?> finalprice" value="<?php echo $att_price+ $productInfo->getFinalPrice() ?>">
				<input type="hidden" class="productid" value="<?php echo $att_price+ $productInfo->getId(); ?>">

				<input type="hidden" class="old_price_<?php echo $childrenId.'_'.$_product->getId();?>" value="<?php echo $productInfo->getPrice() + $att_price ?>">
				</div>
			<?php }else{ ?>
				--
			<?php } ?>
			</td>
			<?php if($hidePrice): ?>
				<?php if (in_array("subtotal", $groupAttribute)): ?>
					<td class="a-center config-subtotal price total_<?php echo $childrenId.'_'.$_product->getId();?>" data-th="Subtotal">
						<?php echo '<span>'.$finalsubtotal.'</span>' ?>
					</td>
				<?php endif; ?>
			<?php endif; ?>

			<?php if($eachRowAddtocart) { ?>
				<td class="a-center cart-btn">
				<?php if ($qty_label != 'Out of stock'){ ?>
				<?php
					$productInfos = $obj->create('Magento\Catalog\Model\Product')->load($block->getProduct()->getId());
					$postParams = $block->getAddToCartPostParams($productInfos);
					$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
				?>




				<?php
					$att_price = 0;
					foreach($productVal['attributes'] as $att) {
						$hidden_super_val = '<input type="hidden" name="super_attribute['.$childrenId.']['.$att['attribute_id'].']" class="cws-attribute-select"  value="'.$att['option_id'].'" data-label="'.$att['attribute_id'].'" data-childid ="'.$childrenId.'" form="saveForm">';
						 echo $hidden_super_val;  } ?>
						 <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>" name="saveForm">
						 <input type="hidden" class="<?php echo "cws-".$childrenId; ?>" value="<?php echo "cws-".$childrenId; ?>" name="row_name[<?php echo $childrenId; ?>]" name="saveForm">
						 <input type="hidden" min="0" data-id="<?php echo $childrenId.'_'.$_product->getId();?>" name="config_table_qty[<?php echo $childrenId; ?>]" value="<?php echo $cartqty; ?>" id="super_group_qty_<?php echo $childrenId;?>_s" <?php echo $disabled; ?>  class="input-text qty config_qty" data-label="<?php echo $childrenId; ?>" name="saveForm">
						 <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>" name="saveForm">

						<?php echo $block->getBlockHtml('formkey')?>


					<button type="submit" title="<?php echo $block->escapeHtml(__('Add All to Cart')); ?>"	class=""  id="savedata" name="saveForm" >
			<span><?php /* @escapeNotVerified */ echo __('Add All to Cart') ?></span>
		</button>


				<?php }else{ ?>
					  <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
				<?php } ?>

				</td>
			<?php } ?>

		</tr>
	<?php $i++; endforeach ?>
</tbody>
</table>

</div>
<?php if($totalOption > ($expandno+1)){ ?>
	<div onclick="expandCollapse()" id="expand-collapse" class="expand-collapse" align="right"><?php echo __('Expand All Options'); ?></div>
<?php } ?>
<?php if($hidePrice): ?>
	<?php if (in_array("subtotal", $groupAttribute)): ?>
		<div class="grandtotal"><?php echo __('Total: '); ?> <span>0.00</span></div>
	<?php endif; ?>
<?php endif; ?>
<?php
	$productInfos = $obj->create('Magento\Catalog\Model\Product')->load($block->getProduct()->getId());
	$postParams = $block->getAddToCartPostParams($productInfos);
	$cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
				?>
<script type="text/javascript">
		require([
			'jquery',
			'uiComponent',
    		'Magento_Customer/js/customer-data'
		],

		function(jQuery, Component, customerData) {

			jQuery('#savedata, #savedataone').on('click', function (event){

				var urldata = "<?php /* @escapeNotVerified */ echo $cartHelper->getAddUrl($block->getProduct()); ?>";
				var dataString = jQuery('#saveForm').serialize();

				jQuery.ajax({
					url : urldata,
					data: dataString,
					dataType: 'json',
					type: 'get',
					showLoader:true,
					success: function(res){
						customerData.reload(['cart']);
						customerData.reload(['messages']);

					}
				});

				jQuery(document).ajaxComplete(function (event, xhr, settings) {
					if (settings.url.indexOf("customer/section/load/?sections=messages") > 0) {
						cartObj = xhr.responseJSON;
		 				var res = JSON.parse(JSON.stringify(xhr));
	     				var responseText = JSON.parse(res.responseText);
						var text = 	responseText.messages.messages[0].text;
						if(responseText.messages.messages[0].type == "success") {
							jQuery('#result').removeClass('error');
							jQuery('#result').addClass('success');
						}else{
							jQuery('#result').removeClass('success');
							jQuery('#result').addClass('error');
						}
						jQuery('#result').html(text);



					}
			    });
			});


		});


	</script>


<script type="text/javascript">
		require([
			'jquery'
		],


		function(jQuery) {

		/*	jQuery(document).on('click', '#product_addtocart_form button', function(e) {
				e.stopPropagation();
    			e.stopImmediatePropagation();
				return;
		 });*/

			jQuery(document).on('click', '.cws', function (event){
				var optID = jQuery(this).attr('option-id');
				var datalabel = jQuery(this).attr('data-label');
				jQuery('.cws').each(function() {
					jQuery('.'+datalabel).removeClass("selected");
				});
				jQuery(this).addClass("selected");

				jQuery('#attribute'+datalabel).val(optID).change();

			});

			/** For mobile browsers - numeric allowed in qty. fix is below **/
			if(/Android|webOS|iPhone|iPad|iPod|Opera Mini/i.test(navigator.userAgent))
			{
			  jQuery(".qty-box").find(".config_qty").prop("type", "number");
			}

		});

		function isNumber(evt) {
			var iKeyCode = (evt.which) ? evt.which : evt.keyCode
			if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57)) {
				return false;
			}
			return true;
		}


	<?php if($totalOption > ($expandno+1)){ ?>
		function expandCollapse() {
			if(jQuery(".toggle_container").css('display') == 'none') {
				jQuery(".toggle_container").show("slow");
				jQuery("#expand-collapse").html("Collapse Options");
				jQuery("#expand-collapse-top").html("Collapse Options");

			} else {
				jQuery(".toggle_container").hide("slow");
				jQuery("#expand-collapse").html("Expand All Options");
				jQuery("#expand-collapse-top").html("Expand All Options");

			}
		}
	<?php } ?>

	</script>
	<script type="text/x-magento-init">
		  {
			"*": {
					  "mbconfigurable_product": {
					  "priceFormat":<?php echo $helper->getPriceFormat(); ?>,
					  "actionUrl":"<?php echo $this->getUrl('wholesaleconfigurable/index/price/'); ?>"
					}
				 }
		  }

	</script>