<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Multiple Wishlist for Magento 2
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div data-amwishlist-js="tabs-block">
    <?= $block->getChildHtml('tabs') ?>
</div>
<?= $block->getChildHtml('new') ?>
<div data-amwishlist-js="content-tabs-block">
    <?= $block->getChildHtml('list') ?>
</div>
