<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Template for displaying grouped product price
 */
?>


<?php

/*
 * Show combined price instead of minimal price for grouped products.
 */

$products = $block->getSaleableItem()->getTypeInstance()->getAssociatedProducts($block->getSaleableItem());

$priceForAll = 0;
$priceForAllOriginal = 0;
foreach ($products as $product) {
    $priceForAll += $product->getFinalPrice();
    $priceForAllOriginal += $product->getPrice('regular_price');
}

?>


<div class="grouped-message" >Achetez ce pack avec une réduction de <?php echo ($priceForAllOriginal - $priceForAll); ?> € !</div>



