<div class="opensi-presentation">
  <h2>OpenSi E-Commerce : la solution de gestion commerciale et de comptabilité pour votre site Magento 2 !</h2>
  <p>Édité par la société Speedinfo, le logiciel de gestion OpenSi E-Commerce apporte un nouveau degré de performance dans la gestion des commandes Magento.<br />Connectable en standard avec la solution Magento, OpenSi E-Commerce permet de contrôler toute l'activité du site e-commerce.</p>
  <p>Grâce à une technologie innovante, les ventes e-commerce sont intégrées automatiquement dans le logiciel sans intervention de votre part. Vous maîtrisez ainsi toute votre activité : commande client, comptabilité, suivi des stocks, gestion des achats, expéditions, réapprovisionnements fournisseur... Sans aucune ressaisie !</p>
  <p><a href="http://www.opensi.fr/logiciel-ecommerce/boutiques-magento">Obtenez une gestion performante dès maintenant !</a></p>
  <center>
    <img src="<?php echo $this->getViewFileUrl("Speedinfo_Opensi::images/magento2_logo.png"); ?>" alt="Magento 2 logo" />
  </center>

  <br /><br />

  <h2>Des fonctionnalités inédites dans la gestion d'une boutique Magento 2</h2>
  <p>Avec OpenSi E-Commerce, il est possible de traiter et de suivre tous les flux d'un site Magento, d'une commande client jusqu'à la comptabilité en passant par la gestion des achats. Disponible en ligne, le logiciel OpenSi E-Commerce est riche en fonctions innovantes pour gérer votre boutique Magento :</p>
  <ul>
  	<li>Validation et préparation des commandes</li>
  	<li>Gestion des expéditions</li>
  	<li>Gestion du drop shipping (livraison directe fournisseur-client)</li>
  	<li>Gestion du réapprovisionnement (manuel ou automatisé)</li>
  	<li>Gestion de la comptabilité</li>
  	<li>Intégration des flux des transporteurs (n° tracking colis)</li>
  	<li>Gestion multi boutiques</li>
  	<li>Suivi des stocks (multi dépôts, inventaire, transfert de stock...)</li>
  	<li>Utilisation de douchette code barre</li>
  	<li>...</li>
  </ul>

  <div class="video"><iframe width="640" height="390" src="https://www.youtube.com/embed/QScWTsM714k" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

  <br /><br />

  <h2>Des bénéfices utilisateurs mesurables au quotidien</h2>
	<p>Utiliser le logiciel de gestion OpenSi E-Commerce au quotidien(*) est l'assurance d'une maîtrise parfaite de l'ensemble de votre gestion commerciale & comptabilité : gain de temps, optimisation financière...</p>

  <table class="benefits">
    <tr>
      <td>
        <h3>Productivité</h3>
        <img src="<?php echo $this->getViewFileUrl("Speedinfo_Opensi::images/productivity.jpg"); ?>" alt="Productivité" />
        Gain de temps dans la préparation des commandes,<br />
        Automatisation du processus de réapprovisionnement,<br />
        Transfert en comptabilité...
      </td>
      <td>
        <h3>Visibilité financière</h3>
        <img src="<?php echo $this->getViewFileUrl("Speedinfo_Opensi::images/visibility.jpg"); ?>" alt="Visibilité financière" />
        Consultation des marges,<br />
        Suivi de la valorisation des stocks,<br />
        Contrôle de la trésorerie...
      </td>
      <td>
        <h3>Qualité</h3>
        <img src="<?php echo $this->getViewFileUrl("Speedinfo_Opensi::images/quality.jpg"); ?>" alt="Qualité" />
        Fiabilité des informations stocks,<br />
        Réduction des délais de livraison,<br />
        Fiabilité des produits expédiés...
      </td>
    </tr>
  </table>

  <br /><br />

  <h2>Un fonctionnement simple et performant</h2>
	<p>OpenSi E-Commerce bénéficie de toute l'expertise des équipes Speedinfo en matière de e-commerce et de gestion de flux.</p>
	<ul>
		<li>Synchronisation du catalogue boutique et de la gestion commerciale (aucune ressaisie)</li>
		<li>Récupération automatique des commandes passées sur la boutique</li>
		<li>Renvoi des statuts de commandes, de la facturation et des stocks vers la boutique</li>
		<li>Génération automatique de documents de vente (bon de livraison, devis...)</li>
		<li>...</li>
	</ul>
	<p><a href="http://www.youtube.com/watch?v=QScWTsM714k" target="_blank">Découvrez OpenSi E-Commerce en images</a></p>

	<br /><br />

	<h2>Speedinfo, un éditeur de logiciels au croisement de la gestion et de l'e-commerce</h2>
	<p>Partenaire privilégié des e-commerçants depuis bientôt 10 ans, la vision de Speedinfo est de proposer des logiciels et des services innovants pour rendre la gestion d'entreprise accessible à tous :</p>
	<ul class="disc">
		<li>OpenSi E-Commerce</li>
		<li>OpenSi Itinerant</li>
		<li>OpenSi Gestion des Contacts</li>
		<li>...</li>
	</ul>

	<p><a href="http://www.opensi.fr" target="_blank">Visitez le site officiel de la solution de gestion OpenSi</a></p>
</div>
