<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_AttrBaseSplitcart
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */?>
<div class="checkout-success">
    <?php
    $viewModel = $block->getCartViewModel();
    $helper = $viewModel->checkoutSession();
    $jsonHelper = $viewModel->getJsonHelper();
    if ($helper->getGuestVertualData([])) {
        $checkoutSession = $jsonHelper->jsonDecode($helper->getGuestVertualData([]));
    }
    
    if ($block->getOrderId()): ?>
                    <?php if ($block->getCanViewOrder()): ?>
            <p>
                        <?=$escaper->escapeHtml(
                            __(
                                'Your order number is: %1.',
                                sprintf(
                                    '<a href="%s" class="order-number"><strong>%s</strong></a>',
                                    $escaper->escapeUrl($block->getViewOrderUrl()),
                                    $block->getOrderId()
                                )
                            ),
                            ['a', 'strong']
                        )?>
            </p>
        <?php else: ?>
            <p><?=$escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span'])?></p>
        <?php endif;?>
            <p>
                <?=$escaper->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.'))?>
            </p>
            <?php endif;?>

    <?=$block->getAdditionalInfoHtml()?>
    <?php if (!empty($checkoutSession)) {?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
            href="<?=$escaper->escapeUrl($block->getUrl('checkout/cart', ['_secure' => true]));?>">
                <span><?=$escaper->escapeHtml(__('Continue To Cart'))?></span>
            </a>
        </div>
    </div>
    <?php } else {?>
        <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?=$escaper->escapeUrl($viewModel->getContinueUrl());?>">
                <span><?=$escaper->escapeHtml(__('Continue Shopping'))?></span>
            </a>
        </div>
    </div>
    <?php }?>
</div>
