<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper" id="features-table">

            <div class="">
                <div class="row">

                    <div class="col-12 att-title">
                        <div class="inner"> <?= $block->escapeHtml(__('Caractéristiques')) ?></div>
                    </div>

            <?php foreach ($_additional as $_data) :?>

            <div class="col-6 product-feature"><div class="inner"><div class="feature-name"><?= $block->escapeHtml($_data['label']) ?></div><div class="feature-value"><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></div></div></div>

            <?php endforeach; ?>
                </div></div>

    </div>
<?php endif;?>
