<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Multiple Wishlist for Magento 2
 */
/** @var \Amasty\MWishlist\Block\Account\Wishlist\Item\Column\Copy $block */
?>

<a class="amwishlist-button -clear"
   title="<?= $block->escapeHtmlAttr(__('Copy Item')) ?>"
   data-mwishlist-ajax='<?= /** @noEscape */ $block->getPostData() ?>'
   data-amwishlist-js="item-copy">
    <?= $block->escapeHtml(__('Copy')) ?>
</a>
